[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { version = "0.3", optional = true, features = ["thread-pool"] }

[features]
default = ['async-pool',]
async-pool = ["futures"]
